version: '3'
services:

  service-1:
    container_name: fuel-prices-api
    build: .
    ports:
      - '5000:3000'
      - '9231:9229'
    environment:
      - PORT=3000
      - NODE_ENV=development
    restart: always
    command: npm start
